server:
  port: 8082
# Spring Boot admin: target
spring:
  boot:
    admin:
      client:
        url: http://localhost:8081
# Spring Actuator: expose all
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
